### ISSUE TITLE
Create chip component

### ISSUE THREAD

**Issue by zmardil** [aflalasker/noble-nikah-frontend#6]
Description

Create a Chip component. Chips are used to fill in the hobbies of the user. Ensure the chips use the correct background colour, font size etc. The chip must be able to take a label and Icon as prop especially so that it can be used in the AutoCompletion component to automatically create chips as the user types in the hobby.

Chips in the editor view will have the "x" icon so that the user can remove it from their hobbies, and others who view user profiles maybe able to see hobbies with a matching icon for the hobby in the chip.

Aashif - share the colour codes, spacing and font spec with Aadil. 

Image of a Chip in the UI design
![Image](https://github.com/aflalasker/noble-nikah-frontend/assets/24475560/9cb2d006-6be4-48e7-90f5-88c25575a0a1)

Link to the MUI component: https://mui.com/material-ui/react-chip/

**Comment by aflalasker** [comment]
@zmardil  - I see that you are working on this at the moment. Take into account the emoji that can be optionally added along with the text. :)
